# Don't touch this value
ConfigVersion: 5

Language:
  # Language files are located in the "lang" folder.
  # The file name is in the format of "{lang}.yml".
  # The default language file is "en_US.yml".
  # If the specified language file does not exist, the default language file will be used.
  # The language file will be reloaded when the server is reloaded.
  DefaultLanguage: "en_US"
  # The language file to be loaded.
  # If the text is empty, the default language file will be used.
  # If don't want to use automatic language switching, please only fill in the language file you want to use.
  LangFiles:
    - "en_US"
    - "zh_TW"

ActionBarDisplay:
  # If enabled, the selected BlockData option will automatically be displayed in the center.
  # Default: true
  AutoToCenter: true
  # ActionBar update interval (tick)
  # Default: 4
  UpdateInterval: 4
DebugStickItem:
  # Options to fill: https://hub.spigotmc.org/javadocs/bukkit/org/bukkit/Material.html
  # Default: "BLAZE_ROD"
  Material: "BLAZE_ROD"
  DisplayName: "<b><gold>Debug Stick</gold></b>"
  Lore:
    - "<dark_gray>Toggle mode using the </dark_gray><b><u><green><key:key.swapOffhand></green></u></b>"
    - "<b><gold>Classic mode</gold></b>: "
    - "Same as regular debugging stick operation:"
    - "<b><green><key:key.attack></green></b> to select the desired data type to modify, "
    - "<b><light_purple><key:key.use></light_purple></b> to change the value of that data."
    - " "
    - "<b><red>Copy mode</red></b>: "
    - "<b><green><key:key.attack></green></b> to select the data of a block to be copied, "
    - "<b><light_purple><key:key.use></light_purple></b> to paste that block's data onto other blocks."
    - " "
    - "<b><blue>Freeze mode</blue></b>: "
    - "<b><light_purple><key:key.use></light_purple></b> to freeze/unfreeze a block, "
    - "<b><green><key:key.attack></green></b> to unfreeze all frozen blocks. "
    - "<i>The status of <u><aqua>frozen blocks</aqua></u> will <u><red>not</red></u> be updated.</i>"
  # If you want to use CustomModelData, please enable it and fill in the CustomModelData value.
  CustomModelData:
    Enabled: false
    CustomModelData: 0

WhitelistWorlds:
  # If enabled, the debug stick will only be available in whitelisted worlds.
  Enabled: false
  Worlds:
    - "*"

BlacklistWorlds:
  # If enabled, the debug stick will be disabled in blacklisted worlds.
  # This option takes precedence over the whitelist.
  Enabled: false
  Worlds:
    - "lobby"

AutoRegionProtection:
  # If enabled, an attempt will be made to automatically support the region protection system.
  Enabled: true

BlockDataFilter:
  Whitelist:
    # If enabled, only the specified block data will be displayed.
    Enabled: false
    # Options to fill in: https://github.com/TWME-TW/DebugStickPro/tree/main/src/main/java/dev/twme/debugstickpro/blockdatautil/subdata
    Whitelist:
      - "*"
  Blacklist:
    # If enabled, the specified block data will not be displayed.
    # This option takes precedence over the whitelist.
    # Default: false
    Enabled: false
    # Options to fill in: https://github.com/TWME-TW/DebugStickPro/tree/main/src/main/java/dev/twme/debugstickpro/blockdatautil/subdata
    Blacklist:
      - "AgeableData"
      - "WaterloggedData"

ModeSetting:
  ClassicMode:
    # If enabled, when switching modes, the selected BlockData type will be cleared.
    # Default: false
    ClearSelectedDataTypeWhenModeChange: false
  CopyMode:
    #If enabled, when switching modes, previously copied BlockData will be cleared.
    # Default: false
    ClearStoredDataWhenModeChange: false
  FreezeMode:
    # If enabled, when switching modes, all frozen blocks will be unfrozen.
    # Default: false
    UnfreezeAllBlockWhenModeChange: false
