# Don't touch this value
ConfigVersion: 1

ActionBarDisplay:
  # If enabled, the selected BlockData option will automatically be displayed in the center.
  AutoToCenter: true
  # ActionBar update interval (tick)
  UpdateInterval: 4
DebugStickItem:
  Material: "BLAZE_ROD"
  DisplayName: "<b><gold>除錯棒</gold></b>"
  Lore:
    - "<dark_gray>使用 </dark_gray><b><u><green><key:key.swapOffhand></green></u></b> <dark_gray>切換模式</dark_gray>"
    - "<b><gold>經典模式</gold></b>: "
    - "與普通除錯棒操作相同："
    - "<b><green><key:key.attack></green></b> 選擇要修改的數據類型，"
    - "<b><light_purple><key:key.use></light_purple></b> 更改該數據的值。"
    - " "
    - "<b><red>複製模式</red></b>: "
    - "<b><green><key:key.attack></green></b> 選擇要複製的方塊數據，"
    - "<b><light_purple><key:key.use></light_purple></b> 將該方塊的數據粘貼到其他方塊上。"
    - " "
    - "<b><blue>凍結模式</blue></b>: "
    - "<b><light_purple><key:key.use></light_purple></b> 凍結/解凍一個方塊，"
    - "<b><green><key:key.attack></green></b> 解凍所有已凍結的方塊。 "
    - "<i>凍結方塊的狀態將不會更新。</i>"

  CustomModelData:
    Enabled: false
    CustomModelData: 0

WhitelistWorlds:
  # If enabled, the debug stick will only be available in whitelisted worlds.
  Enabled: false
  Worlds:
    - "*"

BlacklistWorlds:
  # If enabled, the debug stick will be disabled in blacklisted worlds.
  # This option takes precedence over the whitelist.
  Enabled: false
  Worlds:
    - "lobby"

AutoRegionProtection:
  # If enabled, an attempt will be made to automatically support the region protection system.
  Enabled: true