package dev.twme.debugstickpro.configs;

import dev.twme.debugstickpro.util.blockutil.blockdatautil.subdata.RotatableData;

public class LangFile {
    public class ActionBar {
        public static String SelectedDataFormat = "<b><u>%data%</u></b>";
        public static String formatSelectedData(String data,boolean isUsing){
            if(isUsing)
                return data;
            return SelectedDataFormat.replace("%data%", data);
        }
    }
    public static String AgeableDataName = "Age";
    public static String AnaloguePowerableDataName = "Power";
    public static String AttachableDataName = "Attached";
    public static String BambooDataName = "Leaves";
    public static String BedDataName = "Part";
    public static String BeehiveDataName = "Honey Level";
    public static String BellDataName = "Attachment";
    public static String BigDripleafDataName = "Tilt";
    public static String BisectedDataName = "Half";
    public static String BrewingStandBottle_0DataName = "Bottle 0";
    public static String BrewingStandBottle_1DataName = "Bottle 1";
    public static String BrewingStandBottle_2DataName = "Bottle 2";
    public static String BrushableDataName = "Brushed";
    public static String BubbleColumnDataName = "Drag";
    public static String CakeDataName = "Bites";
    public static String CampfireDataName = "Signal Fire";
    public static String CandleDataName = "Candle Count";
    public static String CaveVinesPlantDataName = "Berries";
    public static String ChestDataName = "Chest Type";
    public static String ChiseledBookshelfSlot_0DataName = "Slot 0";
    public static String ChiseledBookshelfSlot_1DataName = "Slot 1";
    public static String ChiseledBookshelfSlot_2DataName = "Slot 2";
    public static String ChiseledBookshelfSlot_3DataName = "Slot 3";
    public static String ChiseledBookshelfSlot_4DataName = "Slot 4";
    public static String ChiseledBookshelfSlot_5DataName = "Slot 5";
    public static String CommandBlockDataName = "Conditional";
    public static String ComparatorDataName = "Mode";
    public static String CrafterCraftingDataName = "Type";
    public static String CrafterOrientationDataName = "Crafter Orientation";
    public static String CrafterTriggerDataName = "Triggered";
    public static String DaylightDetectorDataName = "Inverted";
    public static String DirectionalDataName = "Direction";
    public static String DispenserDataName = "Triggered";
    public static String DoorDataName = "Door Hinge";
    public static String EndPortalFrameDataName = "Eye";
    public static String FaceAttachableDataName = "Attached Face";
    public static String FarmlandDataName = "Moisture";
    public static String GateDataName = "In Wall";
    public static String HangableDataName = "Hanging";
    public static String HatchableDataName = "Hatch";
    public static String HopperDataName = "Enabled";
    public static String JigsawDataName = "Orientation";
    public static String JukeboxDataName = "Has Record";
    public static String LeavesDistanceDataName = "Distance";
    public static String LeavesPersistentDataName = "Persistent";
    public static String LectronDataName = "Has Book";
    public static String LevelledDataName = "Level";
    public static String LightableDataName = "Lit";
    public static String MultipleFacingDownDataName = "Faces(Down)";
    public static String MultipleFacingEastDataName = "Faces(East)";
    public static String MultipleFacingEastNorthEastDataName = "Faces(East North East)";
    public static String MultipleFacingEastSouthEastDataName = "Faces(East South East)";
    public static String MultipleFacingNorthDataName = "Faces(North)";
    public static String MultipleFacingNorthEastDataName = "Faces(North East)";
    public static String MultipleFacingNorthNorthEastDataName = "Faces(North North East)";
    public static String MultipleFacingNorthNorthWestDataName = "Faces(North North West)";
    public static String MultipleFacingNorthWestDataName = "Faces(North West)";
    public static String MultipleFacingSelfDataName = "Faces(Self)";
    public static String MultipleFacingSouthDataName = "Faces(South)";
    public static String MultipleFacingSouthEastDataName = "Faces(South East)";
    public static String MultipleFacingSouthSouthEastDataName = "Faces(South South East)";
    public static String MultipleFacingSouthSouthWestDataName = "Faces(South South West)";
    public static String MultipleFacingSouthWestDataName = "Faces(South West)";
    public static String MultipleFacingUpDataName = "Faces(Up)";
    public static String MultipleFacingWestDataName = "Faces(West)";
    public static String MultipleFacingWestNorthWestDataName = "Faces(West North West)";
    public static String MultipleFacingWestSouthWestDataName = "Faces(West South West)";
    public static String NoteBlockInstrumentDataName = "Instrument";
    public static String NoteBlockNoteDataName = "Note";
    public static String OrientableDataName = "Axis";
    public static String PinkPetalsDataname = "Flower Amount";
    public static String PistonDataName = "Extended";
    public static String PistonHeadDataName = "ShortArm";
    public static String PointedDripstoneThicknessDataName = "Thickness";
    public static String PointedDripstoneVerticalDirectionDataName = "Vertical Direction";
    public static String PowerableDataName = "Powered";
    public static String RailDataName = "Shape";
    public static String RedstoneWireEastDataName = "East";
    public static String RedstoneWireNorthDataName = "North";
    public static String RedstoneWireSouthDataName = "South";
    public static String RedstoneWireWestDataName = "West";

    public static String RepeaterDelayDataName = "Delay";
    public static String RepeaterLockedDataName = "Locked";
    public static String RespawnAnchorDataName = "Charges";
    public static String RotatableDataName = "Rotation";
    public static String SaplingDataName = "Stage";
    public static String ScaffoldingBottomDataName = "Bottom";
    public static String ScaffoldingDistanceDataName = "Distance";
    public static String SculkCatalystDataName = "Bloom";
    public static String SculkSensorDataName = "Phase";
    public static String SculkShriekerCanSummonDataName = "Can Summon";
    public static String SculkShriekerShriekingDataName = "Shrieking";
    public static String SeaPickleDataName = "Pickles";
    public static String SlabDataName = "Type";
    public static String SnowableDataName = "Snowy";
    public static String SnowDataName = "Layers";
    public static String StairsDataName = "Shape";
    public static String StructureBlockDataName = "Mode";
    public static String TechnicalPistonDataName = "Type";
    public static String TNTDataName = "Unstable";
    public static String TrialSpawnerDataName = "State";
    public static String TripwireDataName = "Disarmed";
    public static String TurtleEggDataName = "Eggs";
    public static String WallHeightEastDataName = "East Height";
    public static String WallHeightNorthDataName = "North Height";
    public static String WallHeightSouthDataName = "South Height";
    public static String WallHeightWestDataName = "West Height";
    public static String WallUpDataName = "Up";
    public static String WaterloggedDataName = "Waterlogged";
}
